# Generated by Django 2.2.2 on 2019-07-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=50)),
                ('main', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=50)),
                ('extras', models.CharField(max_length=50)),
            ],
        ),
    ]
