# Generated by Django 2.2.2 on 2019-07-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=50)),
                ('side', models.CharField(max_length=50)),
                ('extras', models.CharField(max_length=50)),
                ('dishName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seed_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_label', models.CharField(max_length=50)),
                ('rec_yield', models.CharField(max_length=50)),
                ('rec_calories', models.CharField(max_length=50)),
                ('rec_fat_quanity', models.CharField(max_length=50)),
                ('rec_carbs_quanity', models.CharField(max_length=50)),
                ('rec_protein_quanity', models.CharField(max_length=50)),
                ('foodcombo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipe.FoodCombo')),
            ],
        ),
    ]
